# Generated by Django 5.1.7 on 2025-05-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
